"""
Behavioral Cloning Pre-Training
==================================

Trains an ActorDiscretePPO network on expert labels generated by
bc_label_generator.py.  Produces a checkpoint compatible with
AgentDiscreteWyckoffPPO for PPO fine-tuning.

Usage:
  python -m wyckoff_rl.bc_pretrain \
    --labels bc_labels_us30.pt \
    --output bc_actor_us30.pt \
    --epochs 100 --lr 3e-4 --batch-size 1024
"""

from __future__ import annotations

import argparse
import torch as th
import torch.nn as nn
from pathlib import Path

from elegantrl.agents.AgentPPO import ActorDiscretePPO
from elegantrl.agents.AgentBase import build_mlp, layer_init_with_orthogonal

N_ACTIONS = 6


def train_bc(
    labels_path: str,
    output_path: str,
    net_dims: list[int] = None,
    epochs: int = 100,
    lr: float = 3e-4,
    batch_size: int = 1024,
    val_split: float = 0.1,
    device: str = "cuda",
    class_weights: list[float] = None,
):
    """Train ActorDiscretePPO via behavioral cloning."""
    if net_dims is None:
        net_dims = [128, 64]

    # ── Load BC dataset ──────────────────────────────────────────────────
    data = th.load(labels_path, map_location="cpu", weights_only=True)
    states = data["states"]       # (N, state_dim)
    actions = data["actions"]     # (N,)
    state_avg = data["state_avg"] # (state_dim,)
    state_std = data["state_std"] # (state_dim,)

    state_dim = states.shape[1]
    n_total = states.shape[0]
    print(f"Loaded {n_total:,} samples, state_dim={state_dim}")

    # ── Train/val split (time-ordered, no shuffle to avoid leakage) ──────
    n_val = int(n_total * val_split)
    n_train = n_total - n_val
    train_states = states[:n_train]
    train_actions = actions[:n_train]
    val_states = states[n_train:]
    val_actions = actions[n_train:]
    print(f"Train: {n_train:,}, Val: {n_val:,}")

    # ── Class weights ────────────────────────────────────────────────────
    if class_weights is None:
        # Auto-compute inverse frequency weights
        counts = th.zeros(N_ACTIONS)
        for a in range(N_ACTIONS):
            counts[a] = (train_actions == a).sum().float()
        # Inverse frequency, normalized so mean weight = 1
        inv_freq = n_train / (N_ACTIONS * counts.clamp(min=1))
        # Cap max weight to avoid instability
        inv_freq = inv_freq.clamp(max=20.0)
        class_weights = inv_freq
        print(f"Auto class weights: {[f'{w:.1f}' for w in class_weights.tolist()]}")
    else:
        class_weights = th.tensor(class_weights, dtype=th.float32)

    # ── Move to device ───────────────────────────────────────────────────
    dev = th.device(device if th.cuda.is_available() else "cpu")
    train_states = train_states.to(dev)
    train_actions = train_actions.to(dev)
    val_states = val_states.to(dev)
    val_actions = val_actions.to(dev)
    class_weights = class_weights.to(dev)

    # ── Build actor ──────────────────────────────────────────────────────
    actor = ActorDiscretePPO(
        net_dims=net_dims,
        state_dim=state_dim,
        action_dim=N_ACTIONS,
    ).to(dev)

    # Set normalization parameters
    actor.state_avg.data = state_avg.to(dev)
    actor.state_std.data = state_std.to(dev)

    print(f"Actor: {sum(p.numel() for p in actor.parameters()):,} params")

    # ── Loss & optimizer ─────────────────────────────────────────────────
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = th.optim.Adam(actor.net.parameters(), lr=lr)
    scheduler = th.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    # ── Training loop ────────────────────────────────────────────────────
    best_val_acc = 0.0
    best_state = None

    for epoch in range(epochs):
        actor.train()

        # Shuffle training indices each epoch
        perm = th.randperm(n_train, device=dev)
        epoch_loss = 0.0
        n_correct = 0
        n_batches = 0

        for i in range(0, n_train, batch_size):
            idx = perm[i:i + batch_size]
            batch_states = train_states[idx]
            batch_actions = train_actions[idx]

            # Forward: get raw logits (state_norm is applied internally)
            normed = actor.state_norm(batch_states)
            logits = actor.net(normed)

            loss = criterion(logits, batch_actions)
            optimizer.zero_grad()
            loss.backward()
            th.nn.utils.clip_grad_norm_(actor.parameters(), 1.0)
            optimizer.step()

            epoch_loss += loss.item()
            n_correct += (logits.argmax(dim=1) == batch_actions).sum().item()
            n_batches += 1

        scheduler.step()

        train_acc = n_correct / n_train
        avg_loss = epoch_loss / max(n_batches, 1)

        # ── Validation ───────────────────────────────────────────────────
        actor.eval()
        with th.no_grad():
            val_normed = actor.state_norm(val_states)
            val_logits = actor.net(val_normed)
            val_loss = criterion(val_logits, val_actions).item()
            val_preds = val_logits.argmax(dim=1)
            val_acc = (val_preds == val_actions).float().mean().item()

            # Per-class accuracy
            if (epoch + 1) % 10 == 0 or epoch == 0:
                names = ["HOLD", "ENT_L", "ENT_S", "ADD", "REDUCE", "EXIT"]
                cls_str = []
                for a in range(N_ACTIONS):
                    mask = val_actions == a
                    if mask.sum() > 0:
                        cls_acc = (val_preds[mask] == a).float().mean().item()
                        cls_str.append(f"{names[a]}={cls_acc:.0%}")
                    else:
                        cls_str.append(f"{names[a]}=N/A")
                print(f"  Epoch {epoch+1:3d}: loss={avg_loss:.4f} "
                      f"train_acc={train_acc:.1%} val_acc={val_acc:.1%}  "
                      f"[{', '.join(cls_str)}]")
            else:
                print(f"  Epoch {epoch+1:3d}: loss={avg_loss:.4f} "
                      f"train_acc={train_acc:.1%} val_acc={val_acc:.1%}")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = {k: v.cpu().clone() for k, v in actor.state_dict().items()}

    # ── Save best checkpoint ─────────────────────────────────────────────
    print(f"\nBest val accuracy: {best_val_acc:.1%}")

    checkpoint = {
        "actor_state_dict": best_state,
        "state_avg": state_avg,
        "state_std": state_std,
        "net_dims": net_dims,
        "state_dim": state_dim,
        "action_dim": N_ACTIONS,
        "val_acc": best_val_acc,
    }
    th.save(checkpoint, output_path)
    print(f"Saved BC checkpoint to {output_path}")

    return best_val_acc


def main():
    parser = argparse.ArgumentParser(description="BC pre-train ActorDiscretePPO")
    parser.add_argument("--labels", required=True, help="Path to bc_labels_*.pt")
    parser.add_argument("--output", default=None, help="Output checkpoint path")
    parser.add_argument("--net-dims", type=int, nargs="+", default=[128, 64])
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--batch-size", type=int, default=1024)
    parser.add_argument("--val-split", type=float, default=0.1)
    parser.add_argument("--device", default="cuda")
    args = parser.parse_args()

    output = args.output or args.labels.replace("labels", "actor").replace(".pt", "_bc.pt")

    train_bc(
        labels_path=args.labels,
        output_path=output,
        net_dims=args.net_dims,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size,
        val_split=args.val_split,
        device=args.device,
    )


if __name__ == "__main__":
    main()
